const banks=[{name:"Prime National Bank",minCreditScore:"excellent",minIncome:60000,loanTypes:["personal","home","auto"],maxLoanAmount:500000,employmentRequired:["fulltime","selfemployed"],approvalRate:95,interestRate:"3.5% - 5.5%",features:["Low interest rates","Fast approval (24-48 hours)","No prepayment penalty"]},{name:"Community First Credit Union",minCreditScore:"good",minIncome:40000,loanTypes:["personal","auto","home"],maxLoanAmount:300000,employmentRequired:["fulltime","parttime","selfemployed"],approvalRate:85,interestRate:"4.5% - 7.0%",features:["Member-focused service","Flexible terms","Lower fees"]},{name:"Business Growth Bank",minCreditScore:"good",minIncome:50000,loanTypes:["business","personal"],maxLoanAmount:1000000,employmentRequired:["selfemployed","fulltime"],approvalRate:80,interestRate:"5.0% - 8.0%",features:["Business expertise","SBA loan options","Business consulting included"]},{name:"Metro Trust Bank",minCreditScore:"fair",minIncome:35000,loanTypes:["personal","auto","home"],maxLoanAmount:250000,employmentRequired:["fulltime","parttime","selfemployed","retired"],approvalRate:75,interestRate:"6.0% - 9.5%",features:["Accepts fair credit","Multiple loan options","Online application"]},{name:"SecondChance Financial",minCreditScore:"poor",minIncome:25000,loanTypes:["personal","auto"],maxLoanAmount:50000,employmentRequired:["fulltime","parttime","selfemployed"],approvalRate:70,interestRate:"8.5% - 14.0%",features:["Bad credit accepted","Credit building programs","Financial counseling"]},{name:"Education First Bank",minCreditScore:"fair",minIncome:0,loanTypes:["student"],maxLoanAmount:150000,employmentRequired:["fulltime","parttime","selfemployed","unemployed"],approvalRate:90,interestRate:"4.0% - 7.5%",features:["Student-focused","Deferred payment options","Co-signer accepted"]},{name:"Flexible Finance Corp",minCreditScore:"verypoor",minIncome:20000,loanTypes:["personal"],maxLoanAmount:25000,employmentRequired:["fulltime","parttime"],approvalRate:60,interestRate:"12.0% - 18.0%",features:["No credit check options","Quick approval","Small loan specialist"]},{name:"HomeOwner's Bank",minCreditScore:"good",minIncome:55000,loanTypes:["home"],maxLoanAmount:750000,employmentRequired:["fulltime","selfemployed","retired"],approvalRate:85,interestRate:"3.25% - 5.75%",features:["Mortgage specialists","First-time buyer programs","Low down payment options"]}];const creditScoreRank={"excellent":5,"good":4,"fair":3,"poor":2,"verypoor":1};function matchBanks(customerData){const matches=[];banks.forEach(bank=>{let matchScore=0;let reasons=[];if(!bank.loanTypes.includes(customerData.loanType)){return;}
if(creditScoreRank[customerData.creditScore]<creditScoreRank[bank.minCreditScore]){return;}else if(creditScoreRank[customerData.creditScore]>=creditScoreRank[bank.minCreditScore]){matchScore+=25;reasons.push("Credit score meets requirements");}
if(customerData.income<bank.minIncome){return;}else{matchScore+=20;reasons.push("Income qualifies");}
if(customerData.loanAmount>bank.maxLoanAmount){return;}else{matchScore+=15;reasons.push("Loan amount within limits");}
if(!bank.employmentRequired.includes(customerData.employment)){return;}else{matchScore+=15;reasons.push("Employment status accepted");}
if(customerData.creditScore==="excellent"){matchScore+=15;}
if(customerData.income>bank.minIncome*1.5){matchScore+=10;}
matches.push({bank:bank,matchScore:matchScore,reasons:reasons});});matches.sort((a,b)=>b.matchScore-a.matchScore);return matches;}
function displayResults(matches){const resultsContainer=document.getElementById('bankResults');resultsContainer.innerHTML='';if(matches.length===0){resultsContainer.innerHTML=`
            <div class="no-results">
                <h3>No matches found</h3>
                <p>We couldn't find banks that match your current criteria. Consider:</p>
                <ul>
                    <li>Improving your credit score</li>
                    <li>Increasing your income</li>
                    <li>Reducing the loan amount</li>
                    <li>Working with a credit counselor</li>
                </ul>
            </div>
        `;return;}
const topMatches=matches.slice(0,3);topMatches.forEach((match,index)=>{const bank=match.bank;const matchPercentage=Math.min(match.matchScore,100);const approvalLikelihood=Math.min(Math.round(bank.approvalRate*(matchPercentage/100)),bank.approvalRate);let matchClass='high-match';if(matchPercentage<70)matchClass='medium-match';if(matchPercentage<50)matchClass='low-match';const bankCard=document.createElement('div');bankCard.className=`bank-card ${matchClass}`;bankCard.innerHTML=`
            <div class="bank-header">
                <h3>${index + 1}. ${bank.name}</h3>
                <div class="match-badge">
                    <span class="match-percentage">${matchPercentage}%</span>
                    <span class="match-label">Match</span>
                </div>
            </div>
            <div class="bank-info">
                <div class="info-row">
                    <span class="label">Approval Likelihood:</span>
                    <span class="value" style="color: #3ca6d8; font-weight: 700;">${approvalLikelihood}%</span>
                </div>
                <div class="info-row">
                    <span class="label">Interest Rate:</span>
                    <span class="value">${bank.interestRate}</span>
                </div>
                <div class="info-row">
                    <span class="label">Max Loan:</span>
                    <span class="value">$${bank.maxLoanAmount.toLocaleString()}</span>
                </div>
            </div>
            <div class="features">
                <h4>Key Features:</h4>
                <ul>
                    ${bank.features.map(feature => `<li>${feature}</li>`).join('')}
                </ul>
            </div>
            <div class="match-reasons">
                <h4>Why you match:</h4>
                <ul>
                    ${match.reasons.map(reason => `<li>${reason}</li>`).join('')}
                </ul>
            </div>
        `;resultsContainer.appendChild(bankCard);});}
function generateReferenceNumber(){const timestamp=Date.now().toString(36).toUpperCase();const random=Math.random().toString(36).substring(2,7).toUpperCase();return`AXP-${timestamp}-${random}`;}
window.addEventListener('load',function(){if(typeof emailjs!=='undefined'){emailjs.init("VCRoHGxbB5ZkCxxUg");console.log('EmailJS initialized');}else{console.error('EmailJS failed to load');}});document.addEventListener('DOMContentLoaded',function(){const loanForm=document.getElementById('loanForm');const leadForm=document.getElementById('leadForm');const contactForm=document.getElementById('contactForm');function fireEquipmentConversionIfApplicable(){if(window.location.pathname.indexOf('get-matched/equipment')!==-1&&typeof gtag==='function'){gtag('event','conversion',{'send_to':'AW-18021105450/sHHDCNHMioocEKr-kJFD','value':1.0,'currency':'USD'});}}
function handleContactSubmit(e){e.preventDefault();if(typeof emailjs==='undefined'){alert('Email service is not available. Please refresh the page and try again.');return;}
const submitBtn=e.target.querySelector('button[type="submit"]');const originalText=submitBtn.textContent;submitBtn.textContent='Sending...';submitBtn.disabled=true;const subjectSelect=document.getElementById('contactSubject');const subjectText=subjectSelect.options[subjectSelect.selectedIndex].text;const contactData={from_name:document.getElementById('contactName').value,from_email:document.getElementById('contactEmail').value,phone:document.getElementById('contactPhone').value||'Not provided',subject:subjectText,message:document.getElementById('contactMessage').value,to_email:'alex@axiantpartners.com'};var email1=emailjs.send('service_jweh7na','template_xujy2ik',{...contactData,to_email:'alex@axiantpartners.com'});var email2=emailjs.send('service_jweh7na','template_xujy2ik',{...contactData,to_email:'jerry@axiantpartners.com'});Promise.allSettled([email1,email2]).then(function(results){if(results[0].status==='fulfilled'){document.getElementById('contactForm').style.display='none';var ty=document.getElementById('contactThankYou');if(ty)ty.style.display='block';window.scrollTo({top:0,behavior:'smooth'});}else{alert('Sorry, there was an error sending your message. Please email us directly at alex@axiantpartners.com or try again later.');}
submitBtn.textContent=originalText;submitBtn.disabled=false;}).catch(function(err){console.error('Contact form error:',err);alert('Sorry, there was an error sending your message. Please email us directly at alex@axiantpartners.com or try again later.');submitBtn.textContent=originalText;submitBtn.disabled=false;});}
function handleApplicationSubmit(e,isLeadForm){e.preventDefault();const agreeToTerms=document.getElementById('agreeToTerms');if(!agreeToTerms){alert('Form elements not found. Please refresh the page and try again.');console.error('agreeToTerms checkbox not found');return;}
if(!agreeToTerms.checked){alert('Please agree to the Privacy Policy and Terms and Conditions to continue.');agreeToTerms.focus();return;}
if(typeof emailjs==='undefined'){alert('Email service is not available. Please refresh the page and try again.');console.error('EmailJS is not loaded');return;}
const customerData={fullName:document.getElementById('fullName').value,email:document.getElementById('email').value,phone:document.getElementById('phone').value,loanAmount:document.getElementById('loanAmount').value,businessName:document.getElementById('businessName').value,loanType:document.getElementById('loanType').value,creditScore:document.getElementById('creditScore').value,revenue:document.getElementById('revenue').value,yearsInBusiness:document.getElementById('yearsInBusiness').value,equipmentDescription:document.getElementById('equipmentDescription').value};const referenceNumber=generateReferenceNumber();var refEl=document.getElementById('referenceNumber');var leadRefEl=document.getElementById('leadFormReference');if(refEl)refEl.textContent=referenceNumber;if(leadRefEl)leadRefEl.textContent=referenceNumber;const submitButton=e.target.querySelector('button[type="submit"]');const originalButtonText=submitButton.textContent;submitButton.textContent='Submitting...';submitButton.disabled=true;console.log('Sending application email with data:',customerData);const isCobrandedPage=window.location.pathname.includes('rightmfgsystems.html');const urlParams=new URLSearchParams(window.location.search);const vendorEmail=urlParams.get('vendor');if(vendorEmail){console.log('Vendor email detected:',vendorEmail);}else{console.log('No vendor email in URL');}
const emailData={full_name:customerData.fullName,email:customerData.email,phone:customerData.phone,loan_amount:customerData.loanAmount||'Not specified',business_name:customerData.businessName||'Not specified',loan_type:customerData.loanType,credit_score:customerData.creditScore,revenue:customerData.revenue||'Not specified',years_in_business:customerData.yearsInBusiness||'Not specified',equipment_description:customerData.equipmentDescription||'N/A',reference_number:referenceNumber,to_email:'alex@axiantpartners.com'};if(vendorEmail){const decodedVendorEmail=decodeURIComponent(vendorEmail);const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!emailRegex.test(decodedVendorEmail)){console.error('Invalid vendor email format:',decodedVendorEmail);alert('Invalid vendor email in URL. Please contact support.');submitButton.textContent=originalButtonText;submitButton.disabled=false;return;}
console.log('Sending emails to Axiant Partners and vendor:',decodedVendorEmail);console.log('Full URL:',window.location.href);console.log('URL params:',window.location.search);const emailDataWithVendor={...emailData,vendor_email:decodedVendorEmail,vendor_note:`\n\n---\nThis application was submitted through a vendor partnership.\nVendor Email: ${decodedVendorEmail}\nPlease forward this application to the vendor.`};const email1=emailjs.send('service_jweh7na','template_dmwg1ey',{...emailDataWithVendor,to_email:'alex@axiantpartners.com'}).then(function(response){console.log('Email 1 (Axiant) sent successfully:',response);console.log('Response status:',response.status);console.log('Response text:',response.text);return response;}).catch(function(error){console.error('Email 1 (Axiant) failed:',error);console.error('Error status:',error.status);console.error('Error text:',error.text);throw{email:'Axiant',error:error};});const email2=emailjs.send('service_jweh7na','template_dmwg1ey',{...emailData,to_email:decodedVendorEmail}).then(function(response){console.log('Email 2 (Vendor) sent successfully:',response);console.log('Response status:',response.status);console.log('Response text:',response.text);return response;}).catch(function(error){console.error('Email 2 (Vendor) failed:',error);console.error('Vendor email used:',decodedVendorEmail);console.error('Error status:',error.status);console.error('Error text:',error.text);console.error('Note: If this fails, the vendor email may need to be whitelisted in EmailJS service settings.');throw{email:'Vendor',error:error};});Promise.allSettled([email1,email2]).then(function(results){console.log('Email sending results:',results);const axiantResult=results[0];const vendorResult=results[1];if(axiantResult.status==='fulfilled'){console.log('Axiant email sent successfully');}else{console.error('Axiant email failed:',axiantResult.reason);}
if(vendorResult.status==='fulfilled'){console.log('Vendor email sent successfully');}else{console.error('Vendor email failed:',vendorResult.reason);console.error('This might be due to EmailJS template configuration. Make sure the template uses {{to_email}} variable.');}
if(axiantResult.status==='fulfilled'){if(isLeadForm){var lf=document.getElementById('leadForm');var lfTy=document.getElementById('leadFormThankYou');if(lf)lf.style.display='none';if(lf&&lf.nextElementSibling)lf.nextElementSibling.style.display='none';if(lfTy)lfTy.style.display='block';}else{document.getElementById('applicationForm').style.display='none';var sb=document.getElementById('matchStickySubmit');if(sb)sb.style.display='none';var ty=document.getElementById('thankYouContainer');if(ty){ty.style.display=ty.classList.contains('match-thank-you')?'flex':'block';if(ty.classList.contains('match-thank-you')){ty.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}}}
fireEquipmentConversionIfApplicable();if(typeof gtag_report_conversion==='function')gtag_report_conversion();window.scrollTo({top:0,behavior:'smooth'});}else{let errorMessage='Sorry, there was an error submitting your application. ';if(axiantResult.reason&&axiantResult.reason.error&&axiantResult.reason.error.status===412){errorMessage+='The email service connection needs to be updated. Please contact us directly at alex@axiantpartners.com or try again later.';}else{errorMessage+='Please contact us directly at alex@axiantpartners.com or try again later.';}
alert(errorMessage);submitButton.textContent=originalButtonText;submitButton.disabled=false;}});}
else if(isCobrandedPage){const email1=emailjs.send('service_jweh7na','template_dmwg1ey',{...emailData,to_email:'alex@axiantpartners.com'});const email2=emailjs.send('service_jweh7na','template_dmwg1ey',{...emailData,to_email:'ian@mixright.com'});Promise.all([email1,email2]).then(function(responses){console.log('Both emails sent successfully!',responses);if(isLeadForm){var lf=document.getElementById('leadForm');var lfTy=document.getElementById('leadFormThankYou');if(lf)lf.style.display='none';if(lf&&lf.nextElementSibling)lf.nextElementSibling.style.display='none';if(lfTy)lfTy.style.display='block';}else{document.getElementById('applicationForm').style.display='none';var sb=document.getElementById('matchStickySubmit');if(sb)sb.style.display='none';var ty=document.getElementById('thankYouContainer');if(ty){ty.style.display=ty.classList.contains('match-thank-you')?'flex':'block';if(ty.classList.contains('match-thank-you')){ty.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}}}
fireEquipmentConversionIfApplicable();window.scrollTo({top:0,behavior:'smooth'});}).catch(function(error){console.error('Email sending failed:',error);console.error('Error details:',JSON.stringify(error,null,2));let errorMessage='Sorry, there was an error submitting your application. ';if(error.status===412){errorMessage+='The email service connection needs to be updated. Please contact us directly at alex@axiantpartners.com or try again later.';}else{errorMessage+='Please contact us directly at alex@axiantpartners.com or try again later.';}
alert(errorMessage);submitButton.textContent=originalButtonText;submitButton.disabled=false;});}else{var email1=emailjs.send('service_jweh7na','template_dmwg1ey',{...emailData,to_email:'alex@axiantpartners.com'});var email2=emailjs.send('service_jweh7na','template_dmwg1ey',{...emailData,to_email:'jerry@axiantpartners.com'});Promise.allSettled([email1,email2]).then(function(results){var axiantOk=results[0].status==='fulfilled';if(axiantOk){console.log('Application email sent successfully!');if(isLeadForm){var lf=document.getElementById('leadForm');var lfTy=document.getElementById('leadFormThankYou');if(lf)lf.style.display='none';if(lf&&lf.nextElementSibling)lf.nextElementSibling.style.display='none';if(lfTy)lfTy.style.display='block';}else{document.getElementById('applicationForm').style.display='none';var sb=document.getElementById('matchStickySubmit');if(sb)sb.style.display='none';var ty=document.getElementById('thankYouContainer');if(ty){ty.style.display=ty.classList.contains('match-thank-you')?'flex':'block';if(ty.classList.contains('match-thank-you')){ty.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}}}
fireEquipmentConversionIfApplicable();if(typeof gtag_report_conversion==='function')gtag_report_conversion();window.scrollTo({top:0,behavior:'smooth'});}else{console.error('Email sending failed:',results[0].reason);var err=results[0].reason&&results[0].reason.error?results[0].reason.error:{};var errorMessage='Sorry, there was an error submitting your application. ';errorMessage+=(err.status===412)?'The email service connection needs to be updated. ':'';errorMessage+='Please contact us directly at alex@axiantpartners.com or try again later.';alert(errorMessage);submitButton.textContent=originalButtonText;submitButton.disabled=false;}});}}
if(contactForm){contactForm.addEventListener('submit',handleContactSubmit);}
if(loanForm){loanForm.addEventListener('submit',function(e){handleApplicationSubmit(e,false);});var submitBtn=loanForm.querySelector('button[type="submit"]');var stickyBar=document.createElement('div');stickyBar.id='matchStickySubmit';stickyBar.className='match-sticky-submit';stickyBar.setAttribute('aria-hidden','true');stickyBar.innerHTML='<p class="match-sticky-trust">$300M+ funded · Same-day response · Free</p><button type="submit" form="loanForm" class="btn-primary">'+(submitBtn?submitBtn.textContent:'Get Matched')+'</button>';document.body.appendChild(stickyBar);}
if(leadForm){leadForm.addEventListener('submit',function(e){handleApplicationSubmit(e,true);});}
var newContactBtn=document.getElementById('newContactMessage');if(newContactBtn){newContactBtn.addEventListener('click',function(){var form=document.getElementById('contactForm');var ty=document.getElementById('contactThankYou');if(form)form.style.display='';if(ty)ty.style.display='none';if(form)form.reset();window.scrollTo({top:0,behavior:'smooth'});});}
const newApplicationBtn=document.getElementById('newApplication');const thankYouContainer=document.getElementById('thankYouContainer');const matchBackdrop=document.getElementById('matchThankYouBackdrop');function closeMatchThankYouModal(){const appForm=document.getElementById('applicationForm');const ty=document.getElementById('thankYouContainer');const loanForm=document.getElementById('loanForm');var sb=document.getElementById('matchStickySubmit');if(sb)sb.style.display='';if(appForm)appForm.style.display='block';if(ty){ty.style.display='none';ty.setAttribute('aria-hidden','true');}
document.body.style.overflow='';if(loanForm)loanForm.reset();window.scrollTo({top:0,behavior:'smooth'});}
if(newApplicationBtn){newApplicationBtn.addEventListener('click',closeMatchThankYouModal);}
if(matchBackdrop){matchBackdrop.addEventListener('click',closeMatchThankYouModal);}
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&thankYouContainer&&thankYouContainer.classList.contains('match-thank-you')&&thankYouContainer.style.display==='flex'){closeMatchThankYouModal();}});});