#!/usr/bin/env python3
"""Generate axiant-v2-chrome.css - the header, mobile menu and footer only.

The legacy pages (matcher, calculators, get-matched, print pieces) keep their
own stylesheet for the body. Loading all of axiant-v2.css on them is unsafe:
the two sheets share generic class names (.container is the white content card
on those pages) and nine CSS variables (--accent-color, --bg-card,
--text-primary ...). v2 loaded last and redefined them, which flattened those
layouts.

So: take only the chrome rules, scope the generic ones under a chrome root,
and declare the tokens on the chrome roots instead of :root so they never leak
into the page body.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = (ROOT / "axiant-v2.css").read_text(encoding="utf-8")
OUT = ROOT / "axiant-v2-chrome.css"

CHROME = ("utility", "header", "header-bar", "brand", "nav", "nav-toggle",
          "mobile-menu", "mobile-menu-panel", "mobile-menu-head",
          "mobile-menu-close", "mobile-menu-call", "footer", "footer-top",
          "footer-brand", "footer-brand-contact", "footer-col", "footer-bottom",
          "footer-links", "footer-legal", "u-keep", "utility-facts",
          "utility-sep", "dot", "skip-link")
ROOTS = (".utility", ".header", ".mobile-menu", ".footer")
# generic names both sheets use - never emit them unscoped
GENERIC = ("container", "btn", "btn-primary", "btn-secondary", "btn-ghost",
           "btn-lg", "btn-quiet", "eyebrow", "card", "cards")

sel_class = re.compile(r"\.([a-zA-Z][\w-]*)")

def wanted(selector):
    names = set(sel_class.findall(selector))
    return bool(names & set(CHROME))

def scope(selector):
    """Any selector whose leading token is generic gets scoped under each
    chrome root; anything already anchored on chrome is left alone."""
    out = []
    for part in selector.split(","):
        p = part.strip()
        if not p:
            continue
        first = sel_class.search(p.split()[0]) if p.split() else None
        lead = first.group(1) if first else ""
        if lead in GENERIC or p.startswith((":root", "body")) is False and lead == "":
            out.extend("%s %s" % (r, p) for r in ROOTS)
        elif lead in GENERIC:
            out.extend("%s %s" % (r, p) for r in ROOTS)
        else:
            out.append(p)
    return ", ".join(out)

def rules(css):
    """Yield (selector, body, media) - one level of @media nesting is enough."""
    i, n = 0, len(css)
    while i < n:
        at = css.find("@media", i)
        brace = css.find("{", i)
        if brace == -1:
            break
        if at != -1 and at < brace:
            cond_end = css.find("{", at)
            depth, j = 1, cond_end + 1
            while j < n and depth:
                if css[j] == "{": depth += 1
                elif css[j] == "}": depth -= 1
                j += 1
            for sel, body, _ in rules(css[cond_end + 1:j - 1]):
                yield sel, body, css[at:cond_end].strip()
            i = j
            continue
        sel = css[i:brace].strip()
        end = css.find("}", brace)
        if end == -1:
            break
        yield sel, css[brace + 1:end].strip(), None
        i = end + 1

tokens = ""
chunks, media_chunks = [], {}
for sel, body, media in rules(SRC):
    sel_clean = re.sub(r"/\*.*?\*/", "", sel, flags=re.S).strip()
    if not sel_clean:
        continue
    if sel_clean.startswith(":root") and not media:
        tokens += "\n" + body              # every :root block, re-emitted on
        continue                            # the chrome roots (order preserved)
    if not wanted(sel_clean):
        continue
    scoped = scope(sel_clean)
    if not scoped:
        continue
    rule = "%s{%s}" % (scoped, body)
    if media:
        media_chunks.setdefault(media, []).append(rule)
    else:
        chunks.append(rule)

head = ("/* axiant-v2-chrome.css - GENERATED by scripts/build-chrome-css.py.\n"
        "   Header, mobile menu and footer only, for pages that keep the pre-v2\n"
        "   stylesheet for their body. Tokens are declared on the chrome roots,\n"
        "   not :root, so they cannot reach the rest of the page. */\n")
body_css = "%s{%s}\n" % (",".join(ROOTS), tokens) + "\n".join(chunks)
for media, rs in media_chunks.items():
    body_css += "\n%s{\n%s\n}" % (media, "\n".join(rs))
OUT.write_text(head + body_css + "\n", encoding="utf-8")
print("wrote %s (%d KB, %d rules)" % (OUT.name, len(body_css) // 1024, len(chunks) + sum(len(v) for v in media_chunks.values())))
