"""Merge the GSC Coverage drill-down exports into a per-URL action plan.

Inputs:
  - The two GSC Coverage-Drilldown .xlsx files (one per issue type)
  - sitemap.xml (for the universe of "should be indexed" URLs)
  - The triage doc generated by build_triage.py (so we don't re-derive buckets)

Output:
  _analysis/SEO_CLEANUP_ACTIONS_2026-05-27.md — concrete kill/consolidate/keep
  decision for every URL in the not-indexed buckets, grouped by URL pattern.
"""
from __future__ import annotations

import pathlib
import re
from collections import defaultdict

import openpyxl

REPO = pathlib.Path(__file__).resolve().parent.parent
DRILLDOWN_FILES = [
    pathlib.Path(r"C:\Users\alexr\Downloads\https___axiantpartners.com_-Coverage-Drilldown-2026-05-27.xlsx"),
    pathlib.Path(r"C:\Users\alexr\Downloads\https___axiantpartners.com_-Coverage-Drilldown-2026-05-27 (1).xlsx"),
]
ORIGIN = "https://axiantpartners.com"
OUTPUT = REPO / "_analysis" / "SEO_CLEANUP_ACTIONS_2026-05-27.md"


def load_drilldown(path: pathlib.Path) -> tuple[str, list[tuple[str, str]]]:
    wb = openpyxl.load_workbook(path)
    # Metadata sheet -> issue type
    issue = ""
    for row in wb["Metadata"].iter_rows(values_only=True):
        if row and len(row) >= 2 and str(row[0]).lower() == "issue":
            issue = str(row[1]).strip()
    # Table sheet -> (url, last_crawled)
    rows: list[tuple[str, str]] = []
    table = wb["Table"]
    headers = [c.value for c in table[1]]
    for r in table.iter_rows(min_row=2, values_only=True):
        url = str(r[0]).strip() if r[0] else ""
        crawled = str(r[1]) if r[1] else ""
        if url:
            rows.append((url, crawled))
    return issue, rows


def bucket(url: str) -> str:
    path = url.replace(ORIGIN, "")
    rules = [
        ("/equipment-financing/states/", "1A. /equipment-financing/states/* (state pSEO)"),
        ("/equipment-financing/articles/", "1B. /equipment-financing/articles/*"),
        ("/construction-business-financing/", "1C. /construction-business-financing/*"),
        ("/working-capital-loans/articles/", "1D. /working-capital-loans/articles/*"),
        ("/merchant-cash-advance/articles/", "1E. /merchant-cash-advance/articles/*"),
        ("/sba-loans/articles/", "1F. /sba-loans/articles/*"),
        ("/business-line-of-credit/articles/", "1G. /business-line-of-credit/articles/*"),
        ("/business-term-loans/articles/", "1H. /business-term-loans/articles/*"),
        ("/commercial-real-estate-loans/articles/", "1I. /commercial-real-estate-loans/articles/*"),
        ("/trucking-business-financing/", "1J. /trucking-business-financing/*"),
        ("/fix-and-flip/articles/", "1K. /fix-and-flip/articles/*"),
        ("/medical-practices-business-financing/", "1L. /medical-practices-business-financing/*"),
        ("/restaurants-business-financing/", "1M. /restaurants-business-financing/*"),
        ("/manufacturing-business-financing/", "1N. /manufacturing-business-financing/*"),
        ("/landscaping-business-financing/", "1O. /landscaping-business-financing/*"),
        ("/logistics-warehousing-business-financing/", "1P. /logistics-warehousing-business-financing/*"),
        ("/articles/", "1Q. /articles/*"),
        ("/commercial-bridge-loans/articles/", "1R. /commercial-bridge-loans/articles/*"),
        ("/revenue-based-financing/articles/", "1S. /revenue-based-financing/articles/*"),
        ("/securities-based-lending/articles/", "1T. /securities-based-lending/articles/*"),
        ("/startup-financing/articles/", "1U. /startup-financing/articles/*"),
        ("/business-growth/articles/", "1V. /business-growth/articles/*"),
        ("/digital-marketing/articles/", "1W. /digital-marketing/articles/*"),
        ("/get-matched/", "1Y. /get-matched/* (KEEP — lead capture)"),
    ]
    for needle, label in rules:
        if needle in path:
            return label
    if path.endswith(".html"):
        return "1Z. Root .html pages (KEEP — review individually)"
    return "1X. Other / misc"


# Default action recommendation by issue type + bucket
def recommend(issue: str, bucket_label: str) -> str:
    is_crawled_rejected = "Crawled" in issue
    is_state = "states/" in bucket_label
    is_industry_child = bucket_label.startswith(("1C.", "1J.", "1L.", "1M.", "1N.", "1O.", "1P."))
    is_root_html = bucket_label.startswith("1Z.")
    is_lead_capture = bucket_label.startswith("1Y.")

    if is_lead_capture:
        return "**KEEP** — conversion page, not meant to rank"
    if is_root_html:
        return "**KEEP + audit** — likely load-bearing nav page; verify"
    if is_crawled_rejected:
        if is_state:
            return "**KILL (410)** or **301 → /equipment-financing.html** — Google explicitly rejected after crawl"
        if is_industry_child:
            return "**CONSOLIDATE → parent industry hub** — Google rejected after crawl"
        return "**AUDIT + rewrite or kill** — Google crawled and explicitly chose not to index. Worst-quality verdict."
    # Discovered-not-indexed
    if is_state:
        return "**KILL (410)** — never even crawled; no search demand for state-specific equipment financing"
    if is_industry_child:
        return "**CONSOLIDATE → parent industry hub** — no organic demand"
    return "**REVIEW** — low priority for Google; either improve and link internally, or kill"


def main() -> None:
    # Load both drill-down files
    by_issue: dict[str, list[tuple[str, str]]] = {}
    for f in DRILLDOWN_FILES:
        issue, rows = load_drilldown(f)
        by_issue[issue] = rows

    # Build flat lookup: url -> issue
    url_issue: dict[str, str] = {}
    for issue, rows in by_issue.items():
        for url, _ in rows:
            url_issue[url] = issue

    # Now group every flagged URL by bucket, with its issue type
    by_bucket: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for url, issue in url_issue.items():
        by_bucket[bucket(url)].append((url, issue))

    # Render the action doc
    out: list[str] = []
    out.append("# SEO Cleanup Actions — Per-URL Decisions")
    out.append("")
    out.append("**Generated:** 2026-05-27 from GSC Coverage drill-down exports")
    out.append("**Inputs:** 17 \"Crawled — currently not indexed\" + 82 \"Discovered — currently not indexed\" = 99 URLs total")
    out.append("**Companion doc:** `_analysis/SEO_CLEANUP_TRIAGE_2026-05-27.md` (overall strategy + Section 2 title fixes)")
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Issue type cheat sheet")
    out.append("")
    out.append("- **Crawled — currently not indexed (17 URLs):** Google crawled the page and *explicitly chose* not to add it to the index. This is a direct quality verdict — the worst signal a page can have. Highest priority.")
    out.append("- **Discovered — currently not indexed (82 URLs):** Google saw the URL (via sitemap or links) but hasn't bothered crawling it. \"Last crawled: 1969-12-31\" means never. Signals low priority for Google.")
    out.append("")
    out.append("---")
    out.append("")

    # Counts summary
    out.append("## Summary by URL pattern")
    out.append("")
    out.append("| Bucket | Crawled-rejected | Discovered-never-crawled | Default action |")
    out.append("|---|---:|---:|---|")
    summary_rows: list[tuple[str, int, int, str]] = []
    for blabel in sorted(by_bucket.keys()):
        urls = by_bucket[blabel]
        c = sum(1 for _, i in urls if "Crawled" in i)
        d = sum(1 for _, i in urls if "Discovered" in i)
        # Use first URL's issue as a stand-in for action recommendation
        sample_issue = urls[0][1] if urls else ""
        rec = recommend(sample_issue, blabel).split(" — ")[0]
        summary_rows.append((blabel, c, d, rec))
    for blabel, c, d, rec in summary_rows:
        out.append(f"| {blabel} | {c} | {d} | {rec} |")
    out.append("")
    out.append("---")
    out.append("")

    # Per-bucket detail with per-URL recommendation
    for blabel in sorted(by_bucket.keys()):
        urls = by_bucket[blabel]
        out.append(f"## {blabel} — {len(urls)} URLs")
        out.append("")
        # Group by issue within bucket
        crawled = [(u, c) for u, i in urls for c in [url_issue.get(u, "")] if "Crawled" in i]
        # Actually rebuild from original tuple
        crawled_urls = [u for u, i in urls if "Crawled" in i]
        discovered_urls = [u for u, i in urls if "Discovered" in i]
        # Get last_crawled by file load
        if crawled_urls:
            out.append(f"### Crawled — currently not indexed ({len(crawled_urls)})")
            out.append("")
            out.append(f"**Action:** {recommend('Crawled', blabel)}")
            out.append("")
            for u in sorted(crawled_urls):
                out.append(f"- `{u.replace(ORIGIN, '')}`")
            out.append("")
        if discovered_urls:
            out.append(f"### Discovered — currently not indexed ({len(discovered_urls)})")
            out.append("")
            out.append(f"**Action:** {recommend('Discovered', blabel)}")
            out.append("")
            for u in sorted(discovered_urls):
                out.append(f"- `{u.replace(ORIGIN, '')}`")
            out.append("")
        out.append("---")
        out.append("")

    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    print(f"  Buckets: {len(by_bucket)}")
    print(f"  Total flagged URLs: {sum(len(v) for v in by_bucket.values())}")


if __name__ == "__main__":
    main()
